<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="DotNetConfig" Version="1.2.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.SqlServer.DACFx" Version="162.4.92" />
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="161.9142.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReportGenerator.Core" Version="5.3.11" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="NativeHtmlReportTemplate.html">
        <LogicalName>SQLServerCoverage.NativeHtmlReportTemplate.html</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="sp_template.html">
        <LogicalName>SQLServerCoverage.sp_template.html</LogicalName>
    </EmbeddedResource>
</ItemGroup>
</Project>