<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseAppHost>true</UseAppHost>
    <TargetFramework>net8.0</TargetFramework>
    <Version>3.0</Version>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>SQLServerCoverage</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <OutputType>Exe</OutputType>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="DotNetConfig" Version="1.2.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.SqlServer.DACFx" Version="162.4.92" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SQLServerCoverageLib\SQLServerCoverageLib.csproj" />
  </ItemGroup>
</Project>